DROP TABLE IF EXISTS events;
CREATE TABLE events (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  event_description TEXT NOT NULL,
  event_date TIMESTAMP,
  img_url INTEGER REFERENCES events_photos(id),
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);

